### ISSUE TITLE
Minival submission failed for submission

### ISSUE THREAD

**Issue by ruddradev** [facebookresearch/home-robot#411]
## 🐛 Bug

Hi Team, 

I built a docker image on the base docker image of the OVMM baseline and submitted to EvalAI minival submission. The baseline succeeded but the new image failed with the below error - 

```
Loading pretrained CLIP
/opt/conda/envs/home-robot/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1678402412426/work/aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2023-10-04 14:53:57,493 Initializing dataset OVMMDataset-v0
Traceback (most recent call last):
  File "/home-robot/projects/habitat_ovmm/agent.py", line 97, in <module>
    metrics = evaluator.evaluate(
  File "/home-robot/projects/habitat_ovmm/evaluator.py", line 458, in evaluate
    self._env = create_ovmm_env_fn(self.config)
  File "/home-robot/projects/habitat_ovmm/utils/env_utils.py", line 31, in create_ovmm_env_fn
    dataset = make_dataset(habitat_config.dataset.type, config=habitat_config.dataset)
  File "/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/datasets/registration.py", line 26, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/datasets/ovmm/ovmm_dataset.py", line 119, in __init__
    self.viewpoints_matrix = np.load(
  File "/opt/conda/envs/home-robot/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/ovmm/val/viewpoints.npy'
```

I am not sure whether the data needs to be included in the image, as I did not do that earlier. Please advise.

## Steps to Reproduce

EvalAI submission number 309391

**Comment by ruddradev** [comment]
Update: A similar container is running successfully on test-standard. I have resubmitted the docker to minival to check again. It is currently in queue.

**Comment by cpaxton** [comment]
Most likely this is resolved then, if it works on test-standard

**Comment by ruddradev** [comment]
This has not occurred again. Closing issue.
