### ISSUE TITLE
Trouble Downloading Dataset

### ISSUE THREAD

**Issue by eyucherin** [facebookresearch/home-robot#490]
## 🐛 Bug

I am trying to participate in the home-robot challenge and have followed the instructions [here](https://github.com/facebookresearch/home-robot/blob/home-robot-ovmm-challenge-2023-v0.1.2/docs/challenge.md). Everything works up until step 5. Step 6 tells me to download the required data. When I sign into hugging face there is no place to accept the license which won't let me proceed to next steps.

![Screenshot from 2024-04-29 22-29-42](https://github.com/facebookresearch/home-robot/assets/66363530/a956a68a-3d67-486a-bc73-0da4ee658553)

When I try to download the scenes, I get the following. 

```
(habitat) che@che-MS-7D99:~/Desktop/home-robot/projects/habitat_ovmm$  ./install.sh
Download the scenes...
error: pathspec 'data/hssd-hab' did not match any file(s) known to git
Download the objects...
error: pathspec 'data/objects' did not match any file(s) known to git
Download the episodes...
error: pathspec 'data/datasets/ovmm' did not match any file(s) known to git
Safety; make sure you have downloaded everything.
If these are empty, you may have too old a git version.
./install.sh: line 26: cd: /data/hssd-hab: No such file or directory
Could not pull

Errors logged to '/home/che/.git/lfs/logs/20240429T223347.923422473.log'.
Use `git lfs logs last` to view the log.
/home/che
./install.sh: line 30: cd: /data/objects: No such file or directory
Could not pull

Errors logged to '/home/che/.git/lfs/logs/20240429T223347.969110534.log'.
Use `git lfs logs last` to view the log.
/home/che
./install.sh: line 34: cd: /data/datasets/ovmm: No such file or directory
Could not pull

Errors logged to '/home/che/.git/lfs/logs/20240429T223348.014118667.log'.
Use `git lfs logs last` to view the log.
```

## Steps to Reproduce

Follow steps 1~5 in 
[here](https://github.com/facebookresearch/home-robot/blob/home-robot-ovmm-challenge-2023-v0.1.2/docs/challenge.md) and try to download scenes without accepting to license.

## Expected behavior
I should be able to see a place to accept the license for using HSSD scenes in hugging face to download scenes. 

## Additional context
I was able to get a test version of habitat sim to work.

**Comment by yvsriram** [comment]
Thanks you for participating! Happy to help you set up. Can you try downloading outside of the script. `cd data` and  `git clone https://huggingface.co/datasets/hssd/hssd-hab`? Does that work? Entering your huggingface credentials may be necessary.

Also please use [this branch](https://github.com/facebookresearch/home-robot/tree/docker-2024) and [this leaderboard](https://eval.ai/web/challenges/challenge-page/2278/overview) if you want to participate in the CVPR challenge.

**Comment by eyucherin** [comment]
Hi! @yvsriram  Thank you so much for the reply! I just ran `git clone https://huggingface.co/datasets/hssd/hssd-hab` on `cd data`  and I was able to bypass `$HOME_ROBOT_ROOT/projects/habitat_ovmm/install.sh`  part of the dataset setup for OVMM.
However, I still am not able to  run the demo setup. 

ALSO:
When setting up for home_robot_sim, there seems to be an error when downloading pytorch3d. 
```
(home-robot) che@che-MS-7D99:~/Desktop/home-robot$ python -m pip install "git+https://github.com/facebookresearch/pytorch3d.git"
Collecting git+https://github.com/facebookresearch/pytorch3d.git
  Cloning https://github.com/facebookresearch/pytorch3d.git to /tmp/pip-req-build-a5a44a_w
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorch3d.git /tmp/pip-req-build-a5a44a_w
  Resolved https://github.com/facebookresearch/pytorch3d.git to commit 47d5dc88247035b35ca3cfce159565f92d8fbb75
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-a5a44a_w/setup.py", line 15, in <module>
          import torch
        File "/home/che/.conda/envs/home-robot/lib/python3.9/site-packages/torch/__init__.py", line 218, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /home/che/.conda/envs/home-robot/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

Any advice on this would be greatly appreciated!

**Comment by yvsriram** [comment]
Can you try installing it after running `mamba install mkl=2024.0`.

**Comment by eyucherin** [comment]
I am still getting erros after running `mamba install mkl=2024.0` 

for installing `pytorch3d` for the **home-robot simulator,** I still get the following error: 
```     
running build_ext
      **error: [Errno 2] No such file or directory: '/usr/local/cuda-11.7/bin/nvcc'
      [end of output]**
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects
```
AND for running the demo setup to **`OVMM`,** I am getting a new error message after installing mlk=2024.0, I think its related to not being able to install `pytorch3d`. 

```
File "/home/che/.conda/envs/home-robot/lib/python3.9/site-packages/**pytorch3d**/ops/ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```

I currently have Nvidia-smi 550.54.15 with CUDA Version 12.4. I think `pytorch3d` requires cuda-11.7, but this this is running on a container would I still need to downgrade? Any insight on this would be very much appreciated! 
Thank you so much for your help! 

```
(home-robot) che@che-MS-7D99:~/Desktop/home-robot$ nvidia-smi
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+

```

**Comment by yvsriram** [comment]
Hey, I am not entirely sure about this one but you can try a few things if you haven't already.

For the error you are facing:

> File "/home/che/.conda/envs/home-robot/lib/python3.9/site-packages/**pytorch3d**/ops/ball_query.py", line 10, in <module>
>     from pytorch3d import _C
> ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

1. What is the version of your installed pytorch3d? My working environment has `pytorch3d==0.7.5`. You can try pinning to that and see if it helps. 

2. If not done already, it would be good to check that torch and cuda are properly installed and compatible: https://github.com/open-mmlab/mmdetection3d/issues/438#issuecomment-819154481 and also check if any of the solutions from similar issues on [pytorch3d](https://github.com/facebookresearch/pytorch3d/issues/688) are relevant for you? Can you share your `conda env export` so that I can understand your conda environment better?

3. You can try building pytorch3d from source and check if it solves the issue.



> would I still need to downgrade?

We recommend sticking to the CUDA 11.7 and python 3.9. The other dependencies are setup such that they work in this setting. So it may be great if you could downgrade to use cuda 11.7.

Otherwise, it seems like pytorch3d is supported on higher versions of Cuda: https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md too? I am not sure if other dependencies and our code are compatible with cuda 12.4.


Do let us know what works and doesn't work for you.

**Comment by eyucherin** [comment]
Hello! 
I have checked that my environment has pytorch3d == 0.7.5 

Here is my conda env export. 

```
(home-robot) che@che-MS-7D99:~/home-robot$ cat environment.yml
name: home-robot
channels:
  - pytorch3d
  - pytorch
  - pyg
  - aihabitat
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohttp=3.9.5=py39hd1e30aa_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aom=3.9.0=hac33072_0
  - assimp=5.3.1=h8343317_3
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - blas=2.122=openblas
  - blas-devel=3.9.0=22_linux64_openblas
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39h7a31438_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cmake=3.29.2=hcfe8598_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - console_bridge=1.0.2=h924138e_1
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=11.7=h67201e3_3
  - cudatoolkit=11.7.1=h4bc3d14_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=hd590300_0
  - eigen=3.4.0=h4bd325d_0
  - exa=0.10.1=habb4d0f_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=3.2.4=1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h516909a_0
  - frozenlist=1.4.1=py39hd1e30aa_0
  - fsspec=2024.3.1=pyhca7485f_0
  - future=1.0.0=pyhd8ed1ab_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - fzf=0.50.0=ha8f183a_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - gmp=6.3.0=h59595ed_1
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - h5py=3.11.0=nompi_py39h2c511df_100
  - habitat-sim-mutex=1.0=display_bullet
  - habitat-sim-ovmm-challenge-2023=0.2.4=py3.9_bullet_linux
  - harfbuzz=8.4.0=h3d44ed6_0
  - hdf5=1.14.3=nompi_h4f84152_100
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - imageio=2.34.1=pyh4b66e23_0
  - imageio-ffmpeg=0.4.9=pyhd8ed1ab_0
  - iopath=0.1.9=pyhd8ed1ab_0
  - joblib=1.4.0=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h9c3ff4c_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=22_linux64_openblas
  - libboost=1.84.0=h8013b2b_2
  - libboost-devel=1.84.0=h00ab1b0_2
  - libboost-headers=1.84.0=ha770c72_2
  - libboost-python=1.84.0=py39hda80f44_2
  - libboost-python-devel=1.84.0=py39h8003fee_2
  - libcblas=3.9.0=22_linux64_openblas
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.7.1=hca28451_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.120=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=hc881cc4_6
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=13.2.0=h69a702a_6
  - libgfortran5=13.2.0=h43f5ff8_6
  - libglib=2.80.0=hf2295e7_6
  - libhwloc=2.10.0=default_h2fb2949_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - liblapack=3.9.0=22_linux64_openblas
  - liblapacke=3.9.0=22_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libmagma=2.7.2=h09159a4_2
  - libmagma_sparse=2.7.2=h09159a4_3
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.8.0.2=0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libopenvino=2023.2.0=h2e90f83_1
  - libopenvino-auto-batch-plugin=2023.2.0=h59595ed_1
  - libopenvino-auto-plugin=2023.2.0=hd5fc58b_1
  - libopenvino-hetero-plugin=2023.2.0=h3ecfda7_1
  - libopenvino-intel-cpu-plugin=2023.2.0=h2e90f83_1
  - libopenvino-intel-gpu-plugin=2023.2.0=h2e90f83_1
  - libopenvino-ir-frontend=2023.2.0=h3ecfda7_1
  - libopenvino-onnx-frontend=2023.2.0=h59595ed_1
  - libopenvino-paddle-frontend=2023.2.0=h59595ed_1
  - libopenvino-pytorch-frontend=2023.2.0=h59595ed_1
  - libopenvino-tensorflow-frontend=2023.2.0=hfe87413_1
  - libopenvino-tensorflow-lite-frontend=2023.2.0=h59595ed_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.20.3=h3eb15da_0
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h95c4c6d_6
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libva=2.21.0=hd590300_0
  - libvpx=1.14.0=h59595ed_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_2
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=18.1.3=h4dfa4b3_0
  - magma=2.7.2=h2cf16e7_3
  - markupsafe=2.1.5=py39hd1e30aa_0
  - mkl=2024.0.0=ha957f24_49657
  - mkl-devel=2024.0.0=ha770c72_49657
  - mkl-include=2024.0.0=ha957f24_49657
  - multidict=6.0.5=py39hd1e30aa_0
  - ncurses=6.4.20240210=h59595ed_0
  - nettle=3.9.1=h7ab15ed_0
  - ninja=1.12.0=h00ab1b0_0
  - numba=0.59.1=py39h615d6bd_0
  - ocl-icd=2.3.2=hd590300_1
  - ocl-icd-system=1.0.0=1
  - octomap=1.9.8=h924138e_0
  - openblas=0.3.27=pthreads_h7a3da1a_0
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.3.0=hd590300_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.43=hcad00b1_0
  - pinocchio=2.7.1=py39he67e4fc_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - portalocker=2.8.2=py39hf3d152e_1
  - psutil=5.9.8=py39hd1e30aa_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pybind11=2.12.0=py39h7633fee_0
  - pybind11-global=2.12.0=py39h7633fee_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyg=2.5.2=py39_torch_1.13.0_cu117
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.19=h0755675_0_cpython
  - python_abi=3.9=4_cp39
  - pytorch=1.13.1=cpu_py39h92724a6_0
  - pytorch-cluster=1.6.1=py39_torch_1.13.0_cu117
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.1=py39_torch_1.13.0_cu117
  - pytorch3d=0.7.5=py39_cu117_pyt1131
  - pyyaml=6.0.1=py39hd1e30aa_1
  - qhull=2020.2=h4bd325d_2
  - quaternion=2023.0.3=py39h44dd56e_0
  - readline=8.2=h8228510_1
  - rhash=1.4.4=hd590300_0
  - scikit-learn=1.4.2=py39ha22ef79_0
  - scipy=1.13.0=py39h474f0d3_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=hdb0a2a9_1
  - svt-av1=2.0.0=h59595ed_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.12.0=h00ab1b0_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinyxml2=10.0.0=h59595ed_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=0.13.1=py39_cu117
  - torchvision=0.14.1=cpu_py39hcda3413_0
  - tornado=6.4=py39hd1e30aa_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - urdfdom=4.0.0=hee28ff1_1
  - urdfdom_headers=1.1.1=h00ab1b0_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - withbullet=2.0=0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-randrproto=1.5.0=h516909a_1001
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.4.6=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py39hd1e30aa_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
    - absl-py==2.1.0
    - accelerate==0.29.3
    - addict==2.4.0
    - aliyun-python-sdk-core==2.15.1
    - aliyun-python-sdk-kms==2.16.2
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.4.1
    - bagpy==0.5
    - bitarray==2.9.2
    - bitstring==4.2.1
    - black==24.4.2
    - blinker==1.8.1
    - boto3==1.34.97
    - botocore==1.34.97
    - braceexpand==0.1.7
    - cachetools==5.3.3
    - catkin-pkg==1.0.0
    - cfgv==3.4.0
    - chumpy==0.70
    - click==8.1.7
    - cloudpickle==3.0.0
    - cmeel==0.53.3
    - cmeel-assimp==5.3.1
    - cmeel-boost==1.82.0
    - cmeel-console-bridge==1.0.2.2
    - cmeel-octomap==1.9.8.2
    - cmeel-tinyxml==2.6.2.3
    - cmeel-tinyxml2==9.0.0.2
    - cmeel-urdfdom==4.0.0
    - comm==0.2.2
    - configargparse==1.7
    - contourpy==1.2.1
    - crcmod==1.7
    - cryptography==42.0.5
    - cython==3.0.10
    - dash==2.16.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.8.1
    - decorator==4.4.2
    - defusedxml==0.7.1
    - diffusers==0.27.2
    - distlib==0.3.8
    - distro==1.9.0
    - docutils==0.21.2
    - easydict==1.13
    - eigenpy==3.1.3
    - einops==0.8.0
    - empy==4.1
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - faster-fifo==1.4.5
    - fastjsonschema==2.19.1
    - filelock==3.14.0
    - filterpy==1.4.5
    - flask==3.0.3
    - fonttools==4.51.0
    - freetype-py==2.4.0
    - genpy==2022.1
    - gnupg==2.3.1
    - google-auth==2.29.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.62.2
    - gym==0.23.0
    - gym-notices==0.0.8
    - habitat-sim==0.2.5
    - hpp-fcl==2.3.6
    - huggingface-hub==0.22.2
    - hydra-core==1.3.2
    - identify==2.5.36
    - ifcfg==0.24
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - iniconfig==2.0.0
    - ipykernel==6.29.4
    - ipython==8.18.1
    - ipywidgets==8.1.2
    - itsdangerous==2.2.0
    - jedi==0.19.1
    - jinja2==3.0.3
    - jmespath==0.10.0
    - json-tricks==3.17.3
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.10
    - lazy-loader==0.4
    - llvmlite==0.42.0
    - lmdb==1.4.1
    - markdown==3.6
    - markdown-it-py==3.0.0
    - matplotlib==3.8.4
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mmcv-full==1.7.1
    - mmpose==0.28.0
    - model-index==0.1.11
    - moviepy==1.0.3
    - msgpack==1.0.8
    - munkres==1.1.4
    - mypy-extensions==1.0.0
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - nodeenv==1.8.0
    - numpy==1.23.5
    - oauthlib==3.2.2
    - objectio==0.2.29
    - omegaconf==2.3.0
    - open3d==0.18.0
    - opencv-python==4.9.0.80
    - opencv-python-headless==4.9.0.80
    - opendatalab==0.0.10
    - openmim==0.3.9
    - openxlab==0.0.38
    - ordered-set==4.1.0
    - oss2==2.17.0
    - packaging==24.0
    - pandas==2.2.2
    - parso==0.8.4
    - pathspec==0.12.1
    - pexpect==4.9.0
    - pillow==9.5.0
    - pin==2.6.17
    - platformdirs==4.2.1
    - plotly==5.21.0
    - pluggy==1.5.0
    - plyfile==1.0.3
    - pre-commit==3.7.0
    - proglog==0.1.10
    - prompt-toolkit==3.0.43
    - protobuf==3.20.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py3rosmsgs==1.18.2
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pybullet==3.2.6
    - pycocotools==2.0.7
    - pycryptodome==3.20.0
    - pycryptodomex==3.20.0
    - pygifsicle==1.0.7
    - pyglet==1.5.27
    - pygments==2.17.2
    - pyopengl==3.1.0
    - pyquaternion==0.9.9
    - pyrender==0.1.45
    - pyserial==3.5
    - pytest==8.2.0
    - python-dateutil==2.9.0.post0
    - pytools==2024.1.2
    - pytz==2023.4
    - pyzmq==26.0.2
    - referencing==0.35.0
    - regex==2024.4.28
    - requests==2.28.2
    - requests-oauthlib==2.0.0
    - retrying==1.3.4
    - rich==13.4.2
    - rosnumpy==0.0.5.2
    - rospkg==1.5.1
    - rpds-py==0.18.0
    - rsa==4.9
    - s3transfer==0.10.1
    - safetensors==0.4.3
    - scikit-image==0.22.0
    - seaborn==0.13.2
    - setuptools==60.2.0
    - setuptools-scm==8.0.4
    - shellingham==1.5.4
    - simplejson==3.19.2
    - smplx==0.1.28
    - sophuspy==0.0.8
    - stack-data==0.6.3
    - supervision==0.20.0
    - support-developer==1.0.5
    - tenacity==8.2.3
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - tifffile==2024.4.24
    - timm==0.9.16
    - tokenizers==0.19.1
    - tomli==2.0.1
    - torchgeometry==0.1.2
    - tqdm==4.65.2
    - traitlets==5.14.3
    - transformers==4.40.1
    - trimesh==3.23.5
    - typer==0.12.3
    - tzdata==2024.1
    - urllib3==1.26.18
    - virtualenv==20.26.1
    - wcwidth==0.2.13
    - webdataset==0.1.40
    - werkzeug==3.0.2
    - widgetsnbextension==4.0.10
    - xtcocotools==1.14.3
    - yapf==0.40.2
    - zipp==3.18.1
prefix: /home/che/.conda/envs/home-robot
```

**Comment by eyucherin** [comment]
Whenever I try to download the dataset, my all the content on the browser breaks down and I get this error message. Still not able to download wheels for pytorch3d

![Screenshot from 2024-05-03 23-46-20](https://github.com/facebookresearch/home-robot/assets/66363530/884f15b7-ea7a-4a78-8099-423904626a65)

**Comment by eyucherin** [comment]
I was able to fix the above by using this command `MAX_JOBS=1 python -m pip install "git+https://github.com/facebookresearch/pytorch3d.git"` when downloading the dataset. Getting help from [this](https://github.com/facebookresearch/pytorch3d/issues/1770#issuecomment-2029785228) issue
