### ISSUE TITLE
 In branch ``home-robot-ovmm-challenge2024``, to train a new agent from example got error : handle = self._sim.receptacles[``KeyError: 'feb130d3499f00724fa2263e3552d1c70dac6582_:0000|receptacle_mesh_feb130d3499f00724fa2263e3552d1c70dac6582.0000'``

### ISSUE THREAD

**Issue by Yonggie** [facebookresearch/home-robot#498]
## 🐛 Bug

There might be some bug in the training process in ovmm readme at ``projects/habitat_ovmm/README.md``?
The run script is outdated, should be changed (did this according to its hint), otherwise the training won't start:
old:
```
python -u -m habitat_baselines.run \
   --exp-config habitat-baselines/habitat_baselines/config/ovmm/rl_skill.yaml \
   --run-type train benchmark/ovmm=<skill_name> \
   habitat_baselines.checkpoint_folder=data/new_checkpoints/ovmm/<skill_name> -->
```

new:
```
python -u -m habitat_baselines.run\
    --config-name ovmm/rl_discrete_skill.yaml\
    habitat_baselines.evaluate=False  benchmark/ovmm=nav_to_obj\
    habitat_baselines.checkpoint_folder=data/new_checkpoints/ovmm/nav_to_obj
```
With new script, comes some errors about env receptables:
``handle = self._sim.receptacles[KeyError: 'feb130d3499f00724fa2263e3552d1c70dac6582_:0000|receptacle_mesh_feb130d3499f00724fa2263e3552d1c70dac6582.0000``, full log:
```
Traceback (most recent call last):
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 268, in _worker_env
    observations = env.reset()
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/gym/gym_env_episode_count_wrapper.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/gym/gym_env_obs_dict_wrapper.py", line 36, in reset
    return self.env.reset(**kwargs)
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/gym/core.py", line 283, in reset
    return self.env.reset(**kwargs)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/gym/gym_wrapper.py", line 312, in reset
    obs = self.env.reset(*args, return_info=return_info, **kwargs)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/environments.py", line 62, in reset
    return super().reset(*args, return_info=return_info, **kwargs)
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/env.py", line 424, in reset
    observations = self._env.reset()
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/env.py", line 262, in reset
    observations = self.task.reset(episode=self.current_episode)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/tasks/ovmm/sub_tasks/nav_to_obj_task.py", line 53, in reset
    obs = super().reset(episode)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/tasks/rearrange/sub_tasks/nav_to_obj_task.py", line 294, in reset
    return self._get_observations(episode)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/tasks/rearrange/utils.py", line 632, in wrapper
    ret = f(self, *args, **kwargs)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/tasks/rearrange/rearrange_task.py", line 246, in _get_observations
    self.sensor_suite.get_observations(
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/simulator.py", line 237, in get_observations
    return Observations(self.sensors, *args, **kwargs)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/simulator.py", line 130, in __init__
    data.append((uuid, sensor.get_observation(*args, **kwargs)))
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/tasks/ovmm/sub_tasks/nav_to_obj_sensors.py", line 116, in get_observation
    obs[..., 1] = self._get_obs_channel(
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/tasks/ovmm/sub_tasks/nav_to_obj_sensors.py", line 85, in _get_obs_channel

# see the error here!
    handle = self._sim.receptacles[
KeyError: 'feb130d3499f00724fa2263e3552d1c70dac6582_:0000|receptacle_mesh_feb130d3499f00724fa2263e3552d1c70dac6582.0000'
Error executing job with overrides: ['habitat_baselines.evaluate=False', 'benchmark/ovmm=nav_to_obj', 'habitat_baselines.checkpoint_folder=data/new_checkpoints/ovmm/nav_to_obj']
Traceback (most recent call last):
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 77, in <module>
    main()
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 31, in main
    execute_exp(cfg, "eval" if cfg.habitat_baselines.evaluate else "train")
  File "/share/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 60, in execute_exp
    trainer.train()
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 665, in train
    self._init_train(resume_state)
  File "/share/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 282, in _init_train
    observations = self.envs.reset()
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 389, in reset
    results.append(read_fn())
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 110, in __call__
    res = self.read_fn()
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Exception ignored in: <function VectorEnv.__del__ at 0x7faaa757bf70>
Traceback (most recent call last):
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 615, in __del__
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 467, in close
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 110, in __call__
  File "/share/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
  File "/root/mambaforge/envs/habitat-sim/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
EOFError:
```

**Comment by Yonggie** [comment]
Found this object at ``my_data_path/hssd-hab/objects/f/feb130d3499f00724fa2263e3552d1c70dac6582.glb``, with the same object id.

I changed ``num_env`` to ``2`` (previously 20) at ``rl_discrete_skill.yaml`` and everything goes fine. Guess it could be a oom problem again...
