### ISSUE TITLE
Steps to install home_robot core and running hector slam

### ISSUE THREAD

**Issue by vidhiJain** [facebookresearch/home-robot#56]
## 🐛 Bug

I tried setting it up and am running into errors in home_robot install and running hector slam.

## Steps to Reproduce

- Errors in testing home_robot install: What version of `sophus` is required? 
```
(home_robot) hello-robot@stretch-re2-2003:~/home-robot/src/home_robot$ python -m home_robot.nodes.goto_controller
/home/hello-robot/mambaforge/envs/home_robot/bin/python: Error while finding module specification for 'home_robot.nodes.goto_controller' (ModuleNotFoundError: No module named 'home_robot.nodes')
(home_robot) hello-robot@stretch-re2-2003:~/home-robot/src/home_robot$
(home_robot) hello-robot@stretch-re2-2003:~/home-robot/src/home_robot$ python -m home_robot.client.local_hello_robot
Traceback (most recent call last):
  File "/home/hello-robot/mambaforge/envs/home_robot/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hello-robot/mambaforge/envs/home_robot/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hello-robot/home-robot/src/home_robot/home_robot/client/local_hello_robot.py", line 16, in <module>
    import sophus as sp
ModuleNotFoundError: No module named 'sophus'
```
- Error in running hector slam: How to specify the launch files for hector slam?
```
(base) hello-robot@stretch-re2-2003:~/catkin_ws$ roslaunch home_robot startup_stretch_hector_slam.launch
RLException: [startup_stretch_hector_slam.launch] is neither a launch file in package [home_robot] nor is [home_robot] a launch file name
The traceback for the exception was written to the log file.
```

## Expected behavior
Instructions for checking correct setup of `home_robot` core package and running hector-slam.

## Additional context
NA

**Comment by vidhiJain** [comment]
Error after updates:
```
hello-robot@stretch-re2-2003:~/catkin_ws/src/home_robot_hw/launch$ roslaunch home_robot_hw startup_stretch_hector_slam.launch
... logging to /home/hello-robot/.ros/log/85b825f6-b9f2-11ed-80a5-b31cbd894d96/roslaunch-stretch-re2-2003-12589.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://172.26.172.112:43585/

SUMMARY
========

PARAMETERS
 * /aggregator_node/analyzers/hardware/analyzers/Arm/find_and_remove_prefix: ['stretch_driver:...
 * /aggregator_node/analyzers/hardware/analyzers/Arm/path: Arm
 * /aggregator_node/analyzers/hardware/analyzers/Arm/type: diagnostic_aggreg...
 * /aggregator_node/analyzers/hardware/analyzers/Base/find_and_remove_prefix: ['stretch_driver:...
 * /aggregator_node/analyzers/hardware/analyzers/Base/path: Base
 * /aggregator_node/analyzers/hardware/analyzers/Base/type: diagnostic_aggreg...
 * /aggregator_node/analyzers/hardware/analyzers/EndOfArm/find_and_remove_prefix: ['stretch_driver:...
 * /aggregator_node/analyzers/hardware/analyzers/EndOfArm/path: EndOfArm
 * /aggregator_node/analyzers/hardware/analyzers/EndOfArm/type: diagnostic_aggreg...
 * /aggregator_node/analyzers/hardware/analyzers/Head/find_and_remove_prefix: ['stretch_driver:...
 * /aggregator_node/analyzers/hardware/analyzers/Head/path: Head
 * /aggregator_node/analyzers/hardware/analyzers/Head/type: diagnostic_aggreg...
 * /aggregator_node/analyzers/hardware/analyzers/Lift/find_and_remove_prefix: ['stretch_driver:...
 * /aggregator_node/analyzers/hardware/analyzers/Lift/path: Lift
 * /aggregator_node/analyzers/hardware/analyzers/Lift/type: diagnostic_aggreg...
 * /aggregator_node/analyzers/hardware/analyzers/Pimu/find_and_remove_prefix: ['stretch_driver:...
 * /aggregator_node/analyzers/hardware/analyzers/Pimu/path: Pimu
 * /aggregator_node/analyzers/hardware/analyzers/Pimu/type: diagnostic_aggreg...
 * /aggregator_node/analyzers/hardware/analyzers/Wacc/find_and_remove_prefix: ['stretch_driver:...
 * /aggregator_node/analyzers/hardware/analyzers/Wacc/path: Wacc
 * /aggregator_node/analyzers/hardware/analyzers/Wacc/type: diagnostic_aggreg...
 * /aggregator_node/analyzers/hardware/path: Hardware
 * /aggregator_node/analyzers/hardware/type: diagnostic_aggreg...
 * /aggregator_node/path: Stretch
 * /aggregator_node/type: diagnostic_aggreg...
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: 30
 * /camera/realsense2_camera/confidence_height: 480
 * /camera/realsense2_camera/confidence_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /hector_geotiff_node/draw_background_checkerboard: True
 * /hector_geotiff_node/draw_free_space_grid: True
 * /hector_geotiff_node/geotiff_save_period: 0.0
 * /hector_geotiff_node/map_file_base_name: hector_slam_map
 * /hector_geotiff_node/map_file_path: /opt/ros/noetic/s...
 * /hector_geotiff_node/plugins: hector_geotiff_pl...
 * /hector_mapping/advertise_map_service: True
 * /hector_mapping/base_frame: base_link
 * /hector_mapping/laser_z_max_value: 1.0
 * /hector_mapping/laser_z_min_value: -1.0
 * /hector_mapping/map_frame: map
 * /hector_mapping/map_multi_res_levels: 2
 * /hector_mapping/map_resolution: 0.05
 * /hector_mapping/map_size: 2048
 * /hector_mapping/map_start_x: 0.5
 * /hector_mapping/map_start_y: 0.5
 * /hector_mapping/map_update_angle_thresh: 0.06
 * /hector_mapping/map_update_distance_thresh: 0.4
 * /hector_mapping/odom_frame: odom
 * /hector_mapping/pub_map_odom_transform: True
 * /hector_mapping/scan_subscriber_queue_size: 5
 * /hector_mapping/scan_topic: scan
 * /hector_mapping/tf_map_scanmatch_transform_frame_name: scanmatcher_frame
 * /hector_mapping/update_factor_free: 0.4
 * /hector_mapping/update_factor_occupied: 0.9
 * /hector_mapping/use_tf_pose_start_estimate: False
 * /hector_mapping/use_tf_scan_transformation: True
 * /hector_trajectory_server/source_frame_name: scanmatcher_frame
 * /hector_trajectory_server/target_frame_name: /map
 * /hector_trajectory_server/trajectory_publish_rate: 0.25
 * /hector_trajectory_server/trajectory_update_rate: 4.0
 * /joint_state_publisher/rate: 15.0
 * /joint_state_publisher/source_list: ['/stretch/joint_...
 * /laser_filter/scan_filter_chain: [{'name': 'shadow...
 * /laser_scan_matcher_node/fixed_frame: odom
 * /laser_scan_matcher_node/max_angular_correction_deg: 20.0
 * /laser_scan_matcher_node/max_iterations: 10
 * /laser_scan_matcher_node/max_linear_correction: 0.2
 * /laser_scan_matcher_node/use_imu: False
 * /lidar_node/angle_compensate: True
 * /lidar_node/frame_id: laser
 * /lidar_node/inverted: False
 * /lidar_node/scan_mode: Boost
 * /lidar_node/serial_baudrate: 115200
 * /lidar_node/serial_port: /dev/hello-lrf
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 15.0
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /stretch_driver/broadcast_odom_tf: False
 * /stretch_driver/controller_calibration_file: /home/hello-robot...
 * /stretch_driver/fail_out_of_range_goal: False
 * /stretch_driver/mode: navigation
 * /stretch_driver/rate: 15.0
 * /stretch_driver/timeout: 0.5
 * /use_sim_time: False

NODES
  /
    aggregator_node (diagnostic_aggregator/aggregator_node)
    goto_controller (home_robot_hw/goto_controller.py)
    hector_geotiff_node (hector_geotiff/geotiff_node)
    hector_mapping (hector_mapping/hector_mapping)
    hector_trajectory_server (hector_trajectory_server/hector_trajectory_server)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    laser_filter (laser_filters/scan_to_scan_filter_chain)
    laser_scan_matcher_node (laser_scan_matcher/laser_scan_matcher_node)
    lidar_node (rplidar_ros/rplidarNode)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    state_estimator (home_robot_hw/state_estimator.py)
    stretch_driver (stretch_core/stretch_driver)
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://172.26.172.112:11311

process[joint_state_publisher-1]: started with pid [12610]
process[robot_state_publisher-2]: started with pid [12611]
process[stretch_driver-3]: started with pid [12612]
process[aggregator_node-4]: started with pid [12613]
process[camera/realsense2_camera_manager-5]: started with pid [12614]
[ WARN] [1677869046.376022298]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
process[camera/realsense2_camera-6]: started with pid [12620]
process[lidar_node-7]: started with pid [12625]
process[laser_filter-8]: started with pid [12628]
process[laser_scan_matcher_node-9]: started with pid [12634]
process[hector_mapping-10]: started with pid [12640]
[ INFO] [1677869046.416379396]: RPLIDAR running on ROS package rplidar_ros, SDK Version:2.0.0
process[hector_trajectory_server-11]: started with pid [12657]
process[hector_geotiff_node-12]: started with pid [12665]
process[goto_controller-13]: started with pid [12674]
[ INFO] [1677869046.448589621]: Initializing nodelet with 8 worker threads.
[ INFO] [1677869046.463479024]: RPLIDAR S/N: 62CAED93C0EA98C6A5E698F2F7144666
[ INFO] [1677869046.463522981]: Firmware Ver: 1.29
[ INFO] [1677869046.463544526]: Hardware Rev: 7
process[state_estimator-14]: started with pid [12691]
[ INFO] [1677869046.502969378]: Starting LaserScanMatcher
[ INFO] [1677869046.507879366]: Creating application with offscreen platform.
[ INFO] [1677869046.514736774]: RPLidar health status : OK.
[ INFO] [1677869046.517382286]: Created application
[ INFO] [1677869046.545377365]: Waiting for tf transform data between frames /map and scanmatcher_frame to become available
HectorSM map lvl 0: cellLength: 0.05 res x:2048 res y: 2048
[ INFO] [1677869046.644206379]: Successfully initialized hector_geotiff MapWriter plugin TrajectoryMapWriter.
[ INFO] [1677869046.644391161]: Geotiff node started
HectorSM map lvl 1: cellLength: 0.1 res x:1024 res y: 1024
[ INFO] [1677869046.674217843]: HectorSM p_base_frame_: base_link
[ INFO] [1677869046.675208600]: HectorSM p_map_frame_: map
[ INFO] [1677869046.675319776]: HectorSM p_odom_frame_: odom
[ INFO] [1677869046.675384342]: HectorSM p_scan_topic_: scan
[ INFO] [1677869046.675450201]: HectorSM p_use_tf_scan_transformation_: true
[ INFO] [1677869046.675512842]: HectorSM p_pub_map_odom_transform_: true
[ INFO] [1677869046.675580365]: HectorSM p_scan_subscriber_queue_size_: 5
[ INFO] [1677869046.675646249]: HectorSM p_map_pub_period_: 2.000000
[ INFO] [1677869046.675708732]: HectorSM p_update_factor_free_: 0.400000
[ INFO] [1677869046.675770184]: HectorSM p_update_factor_occupied_: 0.900000
[ INFO] [1677869046.675836030]: HectorSM p_map_update_distance_threshold_: 0.400000 
[ INFO] [1677869046.675900126]: HectorSM p_map_update_angle_threshold_: 0.060000
[ INFO] [1677869046.675990098]: HectorSM p_laser_z_min_value_: -1.000000
[ INFO] [1677869046.676054319]: HectorSM p_laser_z_max_value_: 1.000000
[ INFO] [1677869046.728869504]: RealSense ROS v2.3.2
[ INFO] [1677869046.728899763]: Built with LibRealSense v2.50.0
[ INFO] [1677869046.728925072]: Running with LibRealSense v2.50.0
[ INFO] [1677869046.794093082]:  
[ INFO] [1677869046.830080821]: current scan mode: Boost, sample rate: 8 Khz, max_distance: 12.0 m, scan frequency:10.0 Hz, 
Traceback (most recent call last):
  File "/home/hello-robot/catkin_ws/src/home_robot_hw/home_robot_hw/nodes/goto_controller.py", line 17, in <module>
    from home_robot.control.goto_controller import GotoVelocityController
ModuleNotFoundError: No module named 'home_robot'
================================================================================REQUIRED process [goto_controller-13] has died!
process has died [pid 12674, exit code 1, cmd /home/hello-robot/catkin_ws/src/home_robot_hw/home_robot_hw/nodes/goto_controller.py __name:=goto_controller __log:=/home/hello-robot/.ros/log/85b825f6-b9f2-11ed-80a5-b31cbd894d96/goto_controller-13.log].
log file: /home/hello-robot/.ros/log/85b825f6-b9f2-11ed-80a5-b31cbd894d96/goto_controller-13*.log
Initiating shutdown!
================================================================================
[state_estimator-14] killing on exit
[goto_controller-13] killing on exit
[hector_geotiff_node-12] killing on exit
[hector_trajectory_server-11] killing on exit
[hector_mapping-10] killing on exit
[laser_scan_matcher_node-9] killing on exit
[laser_filter-8] killing on exit
[lidar_node-7] killing on exit
[camera/realsense2_camera-6] killing on exit
[camera/realsense2_camera_manager-5] killing on exit
[aggregator_node-4] killing on exit
[INFO] [rospy.topics]: topicmanager initialized
[stretch_driver-3] killing on exit
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ros/noetic/lib/python3/dist-packages/control_msgs/msg/__init__.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/stretch_driver", line 20, in <module>
    from control_msgs.msg import FollowJointTrajectoryAction
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1525, in find_spec
  File "<frozen importlib._bootstrap_external>", line 156, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
KeyboardInterrupt
[INFO] [rospy.core]: signal_shutdown [atexit]
[robot_state_publisher-2] killing on exit
[joint_state_publisher-1] killing on exit
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
[state_estimator-14] escalating to SIGTERM
shutting down processing monitor...
... shutting down processing monitor complete
done
hello-robot@stretch-re2-2003:~/catkin_ws/src/home_robot_hw/launch$ python -m home_robot.nodes.goto_controller
/usr/bin/python: Error while finding module specification for 'home_robot.nodes.goto_controller' (ModuleNotFoundError: No module named 'home_robot')

```

**Comment by exhaustin** [comment]
1. Re-install home-robot via `pip install -e /path/to/home-robot/src/home_robot`
2. Rebuild catkin_ws and re-source setup.devel

**Comment by cpaxton** [comment]
I think this is resolved?
